BB_XSMILES_FILEPATH = "./DELuminate/xviewer_queries/static_exports/BB_XSMILES.csv"

BB_XSMILES_PLACEHOLDERS_FILEPATH = (
    "./DELuminate/xviewer_queries/static_exports/BB_XSMILES_Placeholders.csv"
)

MAX_NUMBER_OF_DISCONNECTIONS = 100

BLANK_PLACEHOLDER = "[Og]"

NULL_PATTERN = "[Yb][Yb]"

TERMINATE_CHARACTER = "_"

ARTIFICIAL_ISOTOPES = {
    "L": 1000,
    "A": 2000,
    "B": 3000,
    "C": 4000,
    "D": 5000,
    "E": 6000,
}

ARTIFICIAL_ELEMENTS = {
    ("A", "L"): ["[La][Ac]", "[Lr][At]", "[Lv][Am]"],
    ("B", "L"): ["[La][Ba]", "[Lr][Bi]", "[Lv][Bk]"],
    ("C", "L"): ["[La][Ce]", "[Lr][Cf]", "[Lv][Cm]"],
    ("D", "L"): ["[La][Db]", "[Lr][Ds]", "[Lv][Dy]"],
    ("E", "L"): ["[La][Er]", "[Lr][Es]", "[Lv][Eu]"],
    ("A", "B"): ["[Ac][Ba]", "[At][Bi]", "[Am][Bk]"],
    ("A", "C"): ["[Ac][Ce]", "[At][Cf]", "[Am][Cm]"],
    ("A", "D"): ["[Ac][Db]", "[At][Ds]", "[Am][Dy]"],
    ("A", "E"): ["[Ac][Er]", "[At][Es]", "[Am][Eu]"],
    ("B", "C"): ["[Ba][Ce]", "[Bi][Cf]", "[Bk][Cm]"],
    ("B", "D"): ["[Ba][Db]", "[Bi][Ds]", "[Bk][Dy]"],
    ("B", "E"): ["[Ba][Er]", "[Bi][Es]", "[Bk][Eu]"],
    ("C", "D"): ["[Ce][Db]", "[Cf][Ds]", "[Cm][Dy]"],
    ("C", "E"): ["[Ce][Er]", "[Cf][Es]", "[Cm][Eu]"],
    ("D", "E"): ["[Db][Er]", "[Ds][Es]", "[Dy][Eu]"],
}

CONNECTIVITY_HANDLES = {
    "[La][Ac]": "%10",
    "[Lr][At]": "%11",
    "[Lv][Am]": "%12",
    "[La][Ba]": "%13",
    "[Lr][Bi]": "%14",
    "[Lv][Bk]": "%15",
    "[La][Ce]": "%16",
    "[Lr][Cf]": "%17",
    "[Lv][Cm]": "%18",
    "[La][Db]": "%19",
    "[Lr][Ds]": "%20",
    "[Lv][Dy]": "%21",
    "[La][Er]": "%22",
    "[Lr][Es]": "%23",
    "[Lv][Eu]": "%24",
    "[Ac][Ba]": "%25",
    "[At][Bi]": "%26",
    "[Am][Bk]": "%27",
    "[Ac][Ce]": "%28",
    "[At][Cf]": "%29",
    "[Am][Cm]": "%30",
    "[Ac][Db]": "%31",
    "[At][Ds]": "%32",
    "[Am][Dy]": "%33",
    "[Ac][Er]": "%34",
    "[At][Es]": "%35",
    "[Am][Eu]": "%36",
    "[Ba][Ce]": "%37",
    "[Bi][Cf]": "%38",
    "[Bk][Cm]": "%39",
    "[Ba][Db]": "%40",
    "[Bi][Ds]": "%41",
    "[Bk][Dy]": "%42",
    "[Bi][Es]": "%43",
    "[Bk][Eu]": "%44",
    "[Ce][Db]": "%45",
    "[Cf][Ds]": "%46",
    "[Cm][Dy]": "%47",
    "[Ce][Er]": "%48",
    "[Cf][Es]": "%49",
    "[Cm][Eu]": "%50",
    "[Db][Er]": "%51",
    "[Ds][Es]": "%52",
    "[Dy][Eu]": "%53",
    # Repeat mappings with elements in reverse order
    # This is done in case the order changes upon conversion to a RDKit mol.
    "[Ac][La]": "%10",
    "[At][Lr]": "%11",
    "[Am][Lv]": "%12",
    "[Ba][La]": "%13",
    "[Bi][Lr]": "%14",
    "[Bk][Lv]": "%15",
    "[Ce][La]": "%16",
    "[Cf][Lr]": "%17",
    "[Cm][Lv]": "%18",
    "[Db][La]": "%19",
    "[Ds][Lr]": "%20",
    "[Dy][Lv]": "%21",
    "[Er][La]": "%22",
    "[Es][Lr]": "%23",
    "[Eu][Lv]": "%24",
    "[Ba][Ac]": "%25",
    "[Bi][At]": "%26",
    "[Bk][Am]": "%27",
    "[Ce][Ac]": "%28",
    "[Cf][At]": "%29",
    "[Cm][Am]": "%30",
    "[Db][Ac]": "%31",
    "[Ds][At]": "%32",
    "[Dy][Am]": "%33",
    "[Er][Ac]": "%34",
    "[Es][At]": "%35",
    "[Eu][Am]": "%36",
    "[Ce][Ba]": "%37",
    "[Cf][Bi]": "%38",
    "[Cm][Bk]": "%39",
    "[Db][Ba]": "%40",
    "[Ds][Bi]": "%41",
    "[Dy][Bk]": "%42",
    "[Es][Bi]": "%43",
    "[Eu][Bk]": "%44",
    "[Db][Ce]": "%45",
    "[Ds][Cf]": "%46",
    "[Dy][Cm]": "%47",
    "[Er][Ce]": "%48",
    "[Es][Cf]": "%49",
    "[Eu][Cm]": "%50",
    "[Er][Db]": "%51",
    "[Es][Ds]": "%52",
    "[Eu][Dy]": "%53",
    # Account for the null pattern
    NULL_PATTERN: "%99",
}
